SERVER:
    WMSIP: 192.168.0.188
    PRODUCTION: True
    
ROBOT:
    PRODUCTION: True
    VIRTUAL: False
    #RBTIP: 192.168.0.90
    RBTIP: 172.28.120.34
    CHARGETHRES: 50
    WORKTHRES: 30
    WMSPROD: True


DATABASE:
    SERVER: SMARTLABFNP\SQLEXPRESS
    DB: M8MMiddlewareDB

PRODUCTION:
    REQ_QTY: 20
